<a href="https://colab.research.google.com/github/jsilryan/Chatbot-Practice/blob/master/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

print(torch.__version__)

2.0.1+cu118


**Intro to Tensors**

In [3]:
#scalar tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
#get dimensions
scalar.ndim
scalar.item() # get tensor as int

7

In [13]:
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim) #number of square brackets
print(vector.shape) # 2 * 1


tensor([7, 7])
1
torch.Size([2])


In [17]:
MATRIX = torch.tensor([[3,4], [5,9]])
MATRIX

print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])
print(MATRIX[1])

2
torch.Size([2, 2])
tensor([3, 4])
tensor([5, 9])


In [31]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [12,4,29]],
                       [[23,4,1],
                        [4,2,12],
                        [9,12,23]],
                       [[6,1,9],
                        [5,9,3],
                        [18,2,33]]])
TENSOR1 = torch.tensor([[[1,2,3],
                        [4,5,6]],
                       [[23,4,1],
                        [4,2,12]],
                       [[6,1,9],
                        [5,9,3]]])
TENSOR2 = torch.tensor([[1,2,3],
                        [4,5,6],
                        [4,5,6],
                        [12,4,29]])
TENSOR3 = torch.tensor([[2,3], [2,5], [2,1],
                        [4,3], [4,5], [4,1],
                        [1,3], [1,5], [1,1]])
TENSOR4 = torch.tensor([[[2,3,4], [2,5,4], [2,1,4],
                        [4,3,9], [4,5,9], [4,1,9],
                        [1,3,1], [1,5,1], [1,1,1]],

                        [[2,3,4], [2,5,4], [2,1,4],
                        [4,3,9], [4,5,9], [4,1,9],
                        [1,3,1], [1,5,1], [1,1,1]],

                        [[2,3,4], [2,5,4], [2,1,4],
                        [4,3,9], [4,5,9], [4,1,9],
                        [1,3,1], [1,5,1], [1,1,1]],])
print(TENSOR4.ndim)
print(TENSOR4.shape)

3
torch.Size([3, 9, 3])


###Random Tensors

Many neural networks learn by starting with tensors full of random numbers and adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update`

In [33]:
#Create a random tensor of shape, size(3,4)
random_tensor = torch.rand(4, 3, 4)
random_tensor

tensor([[[0.7310, 0.6141, 0.6870, 0.6601],
         [0.6249, 0.6654, 0.2348, 0.2746],
         [0.3806, 0.6723, 0.9492, 0.5059]],

        [[0.4937, 0.7073, 0.6820, 0.2040],
         [0.0477, 0.6466, 0.7802, 0.9967],
         [0.5352, 0.0287, 0.4256, 0.9823]],

        [[0.6956, 0.0933, 0.5306, 0.2313],
         [0.5875, 0.2024, 0.1526, 0.1251],
         [0.0049, 0.5442, 0.8092, 0.7385]],

        [[0.9909, 0.1220, 0.1701, 0.4108],
         [0.4896, 0.5609, 0.9754, 0.9559],
         [0.1925, 0.9737, 0.2000, 0.0384]]])

In [37]:
#Random tensor with similar shape to image tensor
rand_image = torch.rand(size = (224,224,3)) #height, width, colour channels (R,G,B)
rand_image.shape, rand_image.ndim

(torch.Size([224, 224, 3]), 3)

0s and 1s

In [39]:
zero = torch.zeros(2,2)
zero #multiply it by any tensor to mask the values by changing it to 0

tensor([[0., 0.],
        [0., 0.]])

In [42]:
one = torch.ones(3,3,2)
one

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [41]:
one.dtype #will start out as float numbers

torch.float32

Create a range of tensors and rensors-like

In [49]:
print(torch.range(2, 9))
num = torch.arange(2, 9)
print(num)

print(torch.arange(start = 2, end = 1533, step = 93))

tensor([2., 3., 4., 5., 6., 7., 8., 9.])
tensor([2, 3, 4, 5, 6, 7, 8])
tensor([   2,   95,  188,  281,  374,  467,  560,  653,  746,  839,  932, 1025,
        1118, 1211, 1304, 1397, 1490])


<ipython-input-49-374686151f25>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(2, 9))


Create tensors-like

In [50]:
new_num = torch.zeros_like(input = num)
new_num

tensor([0, 0, 0, 0, 0, 0, 0])

###Tensor DataTypes

In [54]:
float_32 = torch.tensor([3.1, 6.4, 9.1], dtype = None,
                        device = None,
                        requires_grad = False
                         )

In [52]:
float_32.dtype

torch.float32

In [57]:
float_16 = float_32.type(torch.int)
float_16

tensor([3, 6, 9], dtype=torch.int32)

In [58]:
float_16 * float_32

tensor([ 9.3000, 38.4000, 81.9000])