<a href="https://colab.research.google.com/github/jsilryan/Deep-Learning-Practice/blob/master/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

print(torch.__version__)

2.0.1+cu118


**Intro to Tensors**

In [3]:
int_32_tensor = torch.tensor([3,9,1], dtype = torch.int64)
int_32_tensor

tensor([3, 9, 1])

In [4]:
float_16_tensor = torch.tensor([2,4,5], dtype = torch.float16) #long, LongTensor
float_16_tensor


tensor([2., 4., 5.], dtype=torch.float16)

In [5]:
new = float_16_tensor * int_32_tensor
new

tensor([ 6., 36.,  5.], dtype=torch.float16)

`Tensor Datatype Errors`
1. Tensor not right datatype - To get datatype -> **tensor.dtype**
2. Tensors not right shape - **tensor.shape**
3. Tensors not on right device - **tensor.device**


In [6]:
some_tensor = torch.rand(2,3)
some_tensor

tensor([[0.4378, 0.2993, 0.2255],
        [0.1765, 0.7967, 0.6091]])

In [7]:
print(some_tensor.dtype)
print(f"Shape: {some_tensor.shape}" ) # .size() -> function /// shape is an attribute
print(some_tensor.device)

torch.float32
Shape: torch.Size([2, 3])
cpu


**Manipulating Tensors**
Operations:
1. DMAS from BODMAS
2. Multiplication is element-wise
3. Matrix Multiplication

In [8]:
tensor = torch.tensor([2,3,4])
tensor = tensor + 10
tensor

tensor([12, 13, 14])

In [9]:
# Multiply
# tensor * 10 -> does not reassign
tensor = tensor *10
tensor

tensor([120, 130, 140])

In [10]:
# Subtract
tensor - 10

tensor([110, 120, 130])

In [11]:
# Pytorch in-built functions
torch.mul(tensor, 10)

tensor([1200, 1300, 1400])

In [12]:
torch.add(tensor, 10)

tensor([130, 140, 150])

In [13]:
one = torch.tensor([[2,4,5],
                     [3,1,2]])
one.shape

torch.Size([2, 3])

In [14]:
two = torch.tensor([[2,8],[1,5],[3,6], [9,4]])
two.shape

torch.Size([4, 2])

Multiplication:
1. Element-wise Multiplication -> torch.mul(tensor, 10)
2. Matrix Multiplication

Rules:
1. Inner dimensions must match -> (3 , 2) @ (2 , 3)
2. The resulting matrix has the shape of the **outer dimensions**

In [15]:
tensor = torch.tensor([1,2,3])

print(tensor*tensor)

tensor([1, 4, 9])


In [16]:
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [17]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.36 ms, sys: 0 ns, total: 1.36 ms
Wall time: 1.85 ms


tensor(14)

In [18]:
tensor @ tensor #Also matrix multiplication

tensor(14)

In [19]:
# [1,2,3]
1*1 + 2*2 + 3*3

14

In [20]:
%%time
value = 0 #the time of the torch function is faster than coding using basic operators eg for loop
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.75 ms, sys: 0 ns, total: 1.75 ms
Wall time: 1.84 ms


In [21]:
torch.matmul(torch.rand(3, 10), torch.rand(10,3))

tensor([[2.8628, 1.8252, 2.1172],
        [2.9628, 2.4411, 1.8232],
        [3.0625, 2.0443, 2.7738]])

In [22]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#or torch.mm
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

Transpose

We fix the error above by manipulating the shape of one of the tensors using a **transpose**.

It switches the dimensions of a given tensor and rearranges it.
Use `tensor.T`

In [23]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [24]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [25]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [26]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [27]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [28]:
torch.matmul(torch.tensor([[1,2,3]]), torch.tensor([[1],[2],[3]]))

tensor([[14]])

Tensor Aggregation:
Min, Max, Mean, Sum, etc

In [29]:
# Create a tensor
x = torch.arange(5, 100, 10) #Create an tensor from 0 - 100 with a step of 10
x

tensor([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [30]:
x.min(), torch.min(x)

(tensor(5), tensor(5))

In [ ]:
x.max()

In [31]:
#Cant get mean using int64 or Long, hence change the dtype -> float32 or
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [32]:
#Sum
torch.sum(x)

tensor(500)

Find Positional Min and Max

In [33]:
#Find position in tensor that has the min value
x.argmin()

tensor(0)

In [37]:
x[0]

tensor(5)

In [35]:
x.argmax() #Useful when using softmax activation

tensor(9)

In [36]:
x[9]

tensor(95)

Click Run All at Runtime after colab shuts down. However it will stop at the error cell

## Reshaping, stacking, squeezing and unsqueezing
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack - dim = 0) or side by side (hstack - dim = 1) - plain stack
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way.

In [38]:
# Create a tensor
import torch
x = torch.arange(1. ,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [39]:
#Extra dimension - have to be compatible with the previous dimension
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [40]:
x_new = x.reshape(10,1)
x_new, x_new.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [41]:
x_reshaped = x.reshape(5,2) #If I multiply, does it give me the number of elements
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [42]:
#Change view
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [43]:
#Changing z changes x since a view of a tensor shares the same memory as the original input
z[:, 0] = 23
z, x

(tensor([[23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [44]:
#Stack tensors of top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [45]:
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[23., 23., 23., 23.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [51]:
#squeeze - returns a tensor with all dimensions of input size 1 removed
x_reshaped.shape

torch.Size([5, 2])

In [52]:
x_reshaped.squeeze()

tensor([[23.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [55]:
z.squeeze()

tensor([23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [56]:
print(f"Previous tensor: {z}")
print(f"Previous shape: {z.shape}")
print(f"\nNew tensor: {z.squeeze()}")
print(f"\nNew shape: {z.squeeze().shape}")

Previous tensor: tensor([[23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

New shape: torch.Size([10])


In [62]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {z.squeeze()}")
print(f"Previous shape: {z.squeeze().shape}")
z_squeezed = z.squeeze()

#New dimension
z_unsqueezed = z_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {z_unsqueezed}")
print(f"New shape: {z_unsqueezed.shape}")

z_unsqueezed1 = z_squeezed.unsqueeze(dim = 1)
print(f"\nNew tensor: {z_unsqueezed1}")
print(f"New shape: {z_unsqueezed1.shape}")

Previous target: tensor([23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])

New tensor: tensor([[23.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [63]:
#torch.permute - rearranges dimensions of a target tensor in a specified order
#Returns a view of the original tensor input with its dimensions permuted - shares memory

x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

#Permute to rearrange axis or dim order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0 -> 1, 1 -> 2 and 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #colour_channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [79]:
x_original[0,0,0] = 12
x_original[0,0,0], x_permuted[0,0,0]

(tensor(12.), tensor(12.))

## Indexing

In [86]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [87]:
x[0] #zeroth dimension - outer brackets

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [89]:
x[0][0], x[0,0] # dim = 1

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [91]:
x[0, 0, 2]

tensor(3)

In [94]:
x[0,1,1], x[0,2,2]

(tensor(5), tensor(9))

In [95]:
x[:,0] # : selects all of a target dimension

tensor([[1, 2, 3]])

In [97]:
# All values of 0th and 1st dimension but only index 1 of the 2nd
x[:, :, 1]

tensor([[2, 5, 8]])

In [98]:
#All values of 0th dimension but only the first index of 1st and 2nd dimension
x[:, 1, 1]
# With a colon, it selects all dimensions hence square brackets -> [5], but with a zero x[0,1,1], it will just be 5

tensor([5])

In [106]:
#Index 0 of 0th and 1st dim and all values of 2nd
x[0,0,:], x[0,2,2], x[:,:,2]

(tensor([1, 2, 3]), tensor(9), tensor([[3, 6, 9]]))

##Pytorch and Numpy
Data in NumPy, to PyTorch tensor -> `torch.from_numpy(ndarray)`

Tensor -> NumPy - `torch.Tensor.numpy()`

In [113]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
#Convert to float32
tensor32 = torch.from_numpy(array).type(torch.float32)
array, tensor, array.dtype, tensor.dtype, tensor32.dtype
#Default np dtype is float64 while tensor is float32 -> .dtype not .dtype()

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'),
 torch.float64,
 torch.float32)

In [114]:
#Change value of array -> Doesn't change value of tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [115]:
#Tensor to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [116]:
#Change tensor -> Doesn't change value of array
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility
Trying to take random out of random

How a neural network learns:
`Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce randomness in NN and Pytorch we use **random seed**.

Essentially, the random seed flavours the randomness

In [122]:
#Every time we run a rand, it will create new numbers every time
import torch

rand_A = torch.rand(3,4)
rand_B = torch.rand(3,4)

print(rand_A)
print(rand_B)
print(rand_A == rand_B) #If equal True else False

tensor([[0.2029, 0.9549, 0.7000, 0.9865],
        [0.0019, 0.8244, 0.4847, 0.4665],
        [0.3099, 0.9298, 0.5916, 0.9683]])
tensor([[0.3432, 0.1524, 0.8836, 0.1254],
        [0.6244, 0.7432, 0.2603, 0.6742],
        [0.5238, 0.0730, 0.9295, 0.6732]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [125]:
import torch

RANDOM_SEED = 0 #Different flavours of the randomness; any number
torch.manual_seed(RANDOM_SEED) #Sets the seed for generating random numbers
rand_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) #The random_seed works for one block of code hence repeat it before creating the new tensor with rand. Makes the tensor reproducable
rand_D = torch.rand(3,4)
print(rand_C)
print(rand_D)
print(rand_C == rand_D)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch objects on GPUs
GPU -> Faster computation on numbers

1. Google Colab
2. My GPU
3. Cloud Computing